#!/usr/bin/python3

import sys
import webbrowser

pm = str(sys.argv[1]).replace('[','').replace(']','').replace("'",'').replace('"','').replace(',','')
input = str(sys.argv[2:]).replace('[','').replace(']','').replace("'",'').replace('"','').replace(',','')


def usage():
    print("srch is a cmd-line utility to easily search queries on the cmd-line")
    print("srch <platform> <query>")


if pm == "wiki" or pm == "wikipedia":
    wikipedia = 'https://en.wikipedia.org/wiki/' + str(input)
    webbrowser.open(wikipedia)
elif pm == "so" or pm == "stackoverflow":
    stackoverflow = 'https://stackoverflow.com/search?q=' + str(input)
    webbrowser.open(stackoverflow)



usage()
sys.exit()




