#!/usr/bin/python3
# -*- coding: utf-8 -*-
import sys
import webbrowser

pm = str(sys.argv[1]).replace('[','').replace(']','').replace("'",'').replace('"','').replace(',','')
input = str(sys.argv[2:]).replace('[','').replace(']','').replace("'",'').replace('"','').replace(',','')


def usage():
    print("srch is a cmd-line utility to easily search queries on the cmd-line \n")
    print("srch <platform> <query> \n")
    print('''PLATFORM

            wiki,wikipedia         Search wikipedia for query
            so,stackoverflow       Search stackoverflow for query
            g,google               Search google for query
            r,reddit               Search reddit for query
            ghub,github            Search github for query\n''' )


if pm == "wiki" or pm == "wikipedia":
    wikipedia = 'https://en.wikipedia.org/wiki/' + str(input)
    webbrowser.open(wikipedia)
elif pm == "so" or pm == "stackoverflow":
    stackoverflow = 'https://stackoverflow.com/search?q=' + str(input)
    webbrowser.open(stackoverflow)
elif pm == "g" or pm == "google":
    google = 'www.google.com/search?q=' + str(input)
    webbrowser.open(google)
elif pm == "r" or pm == "reddit":
    reddit = 'https://www.reddit.com/search/?q=' + str(input)
    webbrowser.open(reddit)
elif pm == "ghub" or pm =="github":
    github = 'https://github.com/search?q=' + str(input)
    webbrowser.open(github)


usage()
sys.exit()

