#!/usr/bin/python3
# -*- coding: utf-8 -*-
import sys
import webbrowser

pm = sys.argv[1]
input = sys.argv[2:]

args = (' '.join(input))

def usage():
    print("srch - search from the commandline \n")
    print("python srch <platform> <query> \n")
    print('''platforms to search for

            wiki    Search Wikipedia for query
            so      Search StackOverflow for query
            g       Search Google for query
            r       Search Reddit for query
            gh      Search GitHub for query
            devto   Search dev.to for query
            m       Search Medium for query
            yt      Search Youtube for query
            tw      Search Twitter for query
            gfg     Search GeeksforGeeks for query
            stx     Search Stackexchange for query
            q       Search quora for query
            url     Search for url
            fcc     Search freecodecamp for query
            shell   Search explainshell for query
            mdn     Search MDN Web Docs for query


            Usage:

            $ python srch help      # help menu
            
            $ python srch g what is github commit signing\n''' )


def wiki(args):
    wikipedia = 'https://en.wikipedia.org/wiki/' + str(args)
    webbrowser.open(wikipedia)

def stackoverflow(args):
    stackoverflow = 'https://stackoverflow.com/search?q=' + str(args)
    webbrowser.open(stackoverflow)

def google(args):
    google = 'www.google.com/search?q=' + str(args)
    webbrowser.open(google)

def reddit(args):
    reddit = 'https://www.reddit.com/search/?q=' + str(args)
    webbrowser.open(reddit)
    
def github(args):
    github = 'https://github.com/search?q=' + str(args)
    webbrowser.open(github)

def devto(args):  
    devto = 'https://dev.to/search?q=' + str(args)
    webbrowser.open(devto)
    
def medium(args):
    medium = 'https://medium.com/search?q=' + str(args)
    webbrowser.open(medium)

def youtube(args):
    youtube = 'https://www.youtube.com/results?search_query=' + str(args)
    webbrowser.open(youtube)
    
def twitter(args):
    twitter = 'https://twitter.com/search?q=' + str(args)
    webbrowser.open(twitter)
    
def geeksforgeeks(args):
    geeksforgeeks = 'https://www.geeksforgeeks.org/search/?q=' + str(args)
    webbrowser.open(geeksforgeeks)
    
def stackexchange(args):    
    stackexchange = 'https://stackexchange.com/search?q=' + str(args)
    webbrowser.open(stackexchange)
    
def quora(args):
    quora = 'https://www.quora.com/search?q=' + str(args)
    webbrowser.open(quora)

def url(args):
    uri =str(args)
    webbrowser.open(uri)

def freecodecamp(args):
    freecodecamp = 'https://www.freecodecamp.org/news/search/?query=' + str(args)
    webbrowser.open(freecodecamp)

def explainshell(args):
    explainshell = 'https://explainshell.com/explain?cmd=' + str(args)
    webbrowser.open(explainshell)

def mdn(args):
    mozilladocs = 'https://developer.mozilla.org/en-US/search?q=' + str(args)
    webbrowser.open(mozilladocs)

if pm == '--h' or pm == '--help' or pm == '-h' or pm == '-help' or pm == 'help' or pm == 'h':
    usage()
elif pm == "wiki":
    wiki(args)
elif pm == "so":
    stackoverflow(args)
elif pm == "g":
    google(args)
elif pm == "r":
    reddit(args)    
elif pm == "gh":
    github(args)    
elif pm =="devto":
    devto(args)
elif pm == "m":
    medium(args)
elif pm == "yt:
    youtube(args)
elif pm == "tw":
    twitter(args)
elif pm == "gfg":
    geeksforgeeks(args)
elif pm == "stx":
    stackexchange(args)
elif pm == "q":
    quora(args)
elif pm == "url":
    url(args)
elif pm == "fcc":
    freecodecamp(args)
elif pm == "shell":
    explainshell(args)
elif pm == "mdn":
    mdn(args)
else:
    print('Invalid command...\n\n')
    usage()

sys.exit()