#!/usr/bin/python3
# -*- coding: utf-8 -*-
import sys
import webbrowser

import webbrowser
import argparse


parser = argparse.ArgumentParser(description='search from the commandline')
parser.add_argument("-wiki",type=str,help='search google for query')
parser.add_argument("-so",type=str,help='search stack overflow for query')
parser.add_argument("-g",type=str,help='search google for query')
parser.add_argument("-r",type=str,help='search reddit for query')
parser.add_argument("-gh",type=str,help='search github for query')
parser.add_argument("-devto",type=str,help='search devto for query')
parser.add_argument("-m",type=str,help='search medium for query')
parser.add_argument("-yt",type=str,help='search youtube for query')
parser.add_argument("-tw",type=str,help='search twitter for query')
parser.add_argument("-gfg",type=str,help='search geeksforgeeks for query')
parser.add_argument("-stx",type=str,help='search stack exchange for query')
parser.add_argument("-q",type=str,help='search quora for query')
parser.add_argument("-url",type=str,help='search url for query')
parser.add_argument("-fcc",type=str,help='search freecodecamp for query')
parser.add_argument("-shell",type=str,help='search explainshell for query')
parser.add_argument("-mdn",type=str,help='search mozilla developer network for query')

args = parser.parse_args()

if args.g:
    google = 'www.google.com/search?q=' + str(args.g)
    webbrowser.open(google)
elif args.wiki:
    wikipedia = 'https://en.wikipedia.org/wiki/' + str(args.wiki)
    webbrowser.open(wikipedia)
elif args.so:
    stackoverflow = 'https://stackoverflow.com/search?q=' + str(args.so)
    webbrowser.open(stackoverflow)
elif args.r:
    reddit = 'https://www.reddit.com/search/?q=' + str(args.r)
    webbrowser.open(reddit)  
elif args.gh:
    github = 'https://github.com/search?q=' + str(args.gh)
    webbrowser.open(github)
elif args.devto:
    devto = 'https://dev.to/search?q=' + str(args.devto)
    webbrowser.open(devto)    
elif args.m:
    medium = 'https://medium.com/search?q=' + str(args.m)
    webbrowser.open(medium)
elif args.yt:
    youtube = 'https://www.youtube.com/results?search_query=' + str(args.yt)
    webbrowser.open(youtube)
elif args.tw:
    twitter = 'https://twitter.com/search?q=' + str(args.tw)
    webbrowser.open(twitter)    
elif args.gfg:
    geeksforgeeks = 'https://www.geeksforgeeks.org/search/?q=' + str(args.gfg)
    webbrowser.open(geeksforgeeks)
elif args.stx:
    stackexchange = 'https://stackexchange.com/search?q=' + str(args.stx)
    webbrowser.open(stackexchange)
elif args.q:
    quora = 'https://www.quora.com/search?q=' + str(args.q)
    webbrowser.open(quora)
elif args.url:
    uri =str(args.url)
    webbrowser.open(uri)
elif args.fcc:
    freecodecamp = 'https://www.freecodecamp.org/news/search/?query=' + str(args.fcc)
    webbrowser.open(freecodecamp)
elif args.shell:
    explainshell = 'https://explainshell.com/explain?cmd=' + str(args.shell)
    webbrowser.open(explainshell)
elif args.mdn:
    mozilladocs = 'https://developer.mozilla.org/en-US/search?q=' + str(args.mdn)
    webbrowser.open(mozilladocs)
else:
    print('Invalid command...\n\n')
